# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from membrane.v1 import membrane_pb2 as membrane_dot_v1_dot_membrane__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in membrane/v1/membrane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MembraneServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestEvent = channel.unary_unary(
                '/membrane.v1.MembraneService/IngestEvent',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.IngestEventRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.IngestToolOutput = channel.unary_unary(
                '/membrane.v1.MembraneService/IngestToolOutput',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.IngestToolOutputRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.IngestObservation = channel.unary_unary(
                '/membrane.v1.MembraneService/IngestObservation',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.IngestObservationRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.IngestOutcome = channel.unary_unary(
                '/membrane.v1.MembraneService/IngestOutcome',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.IngestOutcomeRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.IngestWorkingState = channel.unary_unary(
                '/membrane.v1.MembraneService/IngestWorkingState',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.IngestWorkingStateRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/membrane.v1.MembraneService/Retrieve',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.RetrieveResponse.FromString,
                _registered_method=True)
        self.RetrieveByID = channel.unary_unary(
                '/membrane.v1.MembraneService/RetrieveByID',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.RetrieveByIDRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.MemoryRecordResponse.FromString,
                _registered_method=True)
        self.Supersede = channel.unary_unary(
                '/membrane.v1.MembraneService/Supersede',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.SupersedeRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.MemoryRecordResponse.FromString,
                _registered_method=True)
        self.Fork = channel.unary_unary(
                '/membrane.v1.MembraneService/Fork',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.ForkRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.MemoryRecordResponse.FromString,
                _registered_method=True)
        self.Retract = channel.unary_unary(
                '/membrane.v1.MembraneService/Retract',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.RetractRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.RetractResponse.FromString,
                _registered_method=True)
        self.Merge = channel.unary_unary(
                '/membrane.v1.MembraneService/Merge',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.MergeRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.MemoryRecordResponse.FromString,
                _registered_method=True)
        self.Reinforce = channel.unary_unary(
                '/membrane.v1.MembraneService/Reinforce',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.ReinforceRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.ReinforceResponse.FromString,
                _registered_method=True)
        self.Penalize = channel.unary_unary(
                '/membrane.v1.MembraneService/Penalize',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.PenalizeRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.PenalizeResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/membrane.v1.MembraneService/GetMetrics',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.MetricsResponse.FromString,
                _registered_method=True)
        self.Contest = channel.unary_unary(
                '/membrane.v1.MembraneService/Contest',
                request_serializer=membrane_dot_v1_dot_membrane__pb2.ContestRequest.SerializeToString,
                response_deserializer=membrane_dot_v1_dot_membrane__pb2.ContestResponse.FromString,
                _registered_method=True)


class MembraneServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestToolOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestOutcome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestWorkingState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Supersede(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Merge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reinforce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Penalize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Contest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MembraneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestEvent,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.IngestEventRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.IngestResponse.SerializeToString,
            ),
            'IngestToolOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestToolOutput,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.IngestToolOutputRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.IngestResponse.SerializeToString,
            ),
            'IngestObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestObservation,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.IngestObservationRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.IngestResponse.SerializeToString,
            ),
            'IngestOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestOutcome,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.IngestOutcomeRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.IngestResponse.SerializeToString,
            ),
            'IngestWorkingState': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestWorkingState,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.IngestWorkingStateRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.IngestResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.RetrieveRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.RetrieveResponse.SerializeToString,
            ),
            'RetrieveByID': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveByID,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.RetrieveByIDRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.MemoryRecordResponse.SerializeToString,
            ),
            'Supersede': grpc.unary_unary_rpc_method_handler(
                    servicer.Supersede,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.SupersedeRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.MemoryRecordResponse.SerializeToString,
            ),
            'Fork': grpc.unary_unary_rpc_method_handler(
                    servicer.Fork,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.ForkRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.MemoryRecordResponse.SerializeToString,
            ),
            'Retract': grpc.unary_unary_rpc_method_handler(
                    servicer.Retract,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.RetractRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.RetractResponse.SerializeToString,
            ),
            'Merge': grpc.unary_unary_rpc_method_handler(
                    servicer.Merge,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.MergeRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.MemoryRecordResponse.SerializeToString,
            ),
            'Reinforce': grpc.unary_unary_rpc_method_handler(
                    servicer.Reinforce,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.ReinforceRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.ReinforceResponse.SerializeToString,
            ),
            'Penalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Penalize,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.PenalizeRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.PenalizeResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.GetMetricsRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.MetricsResponse.SerializeToString,
            ),
            'Contest': grpc.unary_unary_rpc_method_handler(
                    servicer.Contest,
                    request_deserializer=membrane_dot_v1_dot_membrane__pb2.ContestRequest.FromString,
                    response_serializer=membrane_dot_v1_dot_membrane__pb2.ContestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'membrane.v1.MembraneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('membrane.v1.MembraneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MembraneService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/IngestEvent',
            membrane_dot_v1_dot_membrane__pb2.IngestEventRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestToolOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/IngestToolOutput',
            membrane_dot_v1_dot_membrane__pb2.IngestToolOutputRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/IngestObservation',
            membrane_dot_v1_dot_membrane__pb2.IngestObservationRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/IngestOutcome',
            membrane_dot_v1_dot_membrane__pb2.IngestOutcomeRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestWorkingState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/IngestWorkingState',
            membrane_dot_v1_dot_membrane__pb2.IngestWorkingStateRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/Retrieve',
            membrane_dot_v1_dot_membrane__pb2.RetrieveRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/RetrieveByID',
            membrane_dot_v1_dot_membrane__pb2.RetrieveByIDRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.MemoryRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Supersede(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/Supersede',
            membrane_dot_v1_dot_membrane__pb2.SupersedeRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.MemoryRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/Fork',
            membrane_dot_v1_dot_membrane__pb2.ForkRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.MemoryRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/Retract',
            membrane_dot_v1_dot_membrane__pb2.RetractRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.RetractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Merge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/Merge',
            membrane_dot_v1_dot_membrane__pb2.MergeRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.MemoryRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reinforce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/Reinforce',
            membrane_dot_v1_dot_membrane__pb2.ReinforceRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.ReinforceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Penalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/Penalize',
            membrane_dot_v1_dot_membrane__pb2.PenalizeRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.PenalizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/GetMetrics',
            membrane_dot_v1_dot_membrane__pb2.GetMetricsRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Contest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/membrane.v1.MembraneService/Contest',
            membrane_dot_v1_dot_membrane__pb2.ContestRequest.SerializeToString,
            membrane_dot_v1_dot_membrane__pb2.ContestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
